### PR TITLE
Fix: Replace multiline_text fields when prefixed with #replace

### LINKED ISSUE #438: Bug whit "Comment" injection
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### GLPI Version

10.0.17

### Plugin version

2.14.0

### Bug description

Same bug in this post #280 

I have tested with GLPI 10.0.17 and plugin 2.14.0

When I inject text into the "Comment" field, there is no update, but the text is added instead.

Example : Comment in file is "In the bedroom", glpi is "in the saloon"

After the first injection, the comment field shows:
"in the saloon
In the bedroom"

After the second injection, the comment field shows:
"in the saloon
In the bedroom
In the bedroom"

What I need in the comment field is : "In the bedroom"

This bug occurs for all objects with a comment field.

To fix this for computers, I modified the following in

./plugins/datainjection/inc/computerinjection.class.php 
```
        $options['displaytype']   = ["dropdown"       => [3, 4, 23, 31, 32, 33, 40,
            41, 42, 45, 46, 49, 71
        ],
            "user"           => [24, 70]
            /**"multiline_text" => [16, 90]**/
        ];
``` 

Thx       
      

### Relevant log output

_No response_

### Page URL

_No response_

### Steps To reproduce

_No response_

### Your GLPI setup information

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JeremieMercier**
- If a new value for a multiline_text field starts with "#replace", the old value is completely replaced instead of being concatenated.
- The "#replace" tag is removed before storing the new value.
- Default behavior remains unchanged for other cases.

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have performed a self-review of my code.
- [ ] I have added tests (when available) that prove my fix is effective or that my feature works.
- [x] I have updated the CHANGELOG with a short functional description of the fix or new feature.
- [x] This change requires a documentation update.

## Description

- It fixes #438 
- This PR modifies the behavior of multiline_text fields:
    - If a new value starts with #replace, the old value is completely replaced instead of being concatenated.
    - The #replace tag is removed before storing the new value.
    - The default concatenation behavior remains unchanged when the tag is not present.

### CODE REVIEW

**Comment by Mirkk** [comment]
really useful, seems a good idea!

**Comment by stonebuzz** [comment]
Good idea indeed, @Rom1-B  do you see any other solution (apart from adding an enième option, box to coach etc ...)

**Review by Rom1-B — CHANGES_REQUESTED** [review]
The feature is interesting, but I think an option is needed; it would be more explicit for users because, in its current state, it's a hidden feature. Even though it's in the documentation, I doubt that most users will make the effort to read it.

**Comment by JeremieMercier** [comment]
I have added a parameter in the advanced options : "Replacing the value of multiline text fields" (Yes/No).

But, I have some doubts about modifying the hook.php file for the database migration to add the column "multiline_value_replace". Is this the right way to do it ?

File: hook.php [hunk 1]
```diff
@@ -233,6 +236,19 @@ function plugin_datainjection_uninstall()
...
 
+function plugin_datainjection_migration_2141_2150(Migration $migration)
+{
+    $migration->setVersion('2.15.0');
+
+    $migration->addPostQuery(
+        "ALTER TABLE `glpi_plugin_datainjection_models`
+         ADD `multiline_value_replace` tinyint NOT NULL DEFAULT '0'",
+        'Adding multiline_value_replace field to models'
+    );
```
Comment (Rom1-B) [inline hook.php:247]: You can use the dedicated function for adding fields to the database:
```suggestion
    $migration->addField(
        'glpi_plugin_datainjection_models',
        'multiline_value_replace',
        'bool'
    );
```

**Review by Rom1-B — CHANGES_REQUESTED** [review]

File: inc/model.class.php [hunk 2]
```diff
@@ -520,6 +527,14 @@ public function rawSearchOptions()
             'datatype'      => 'bool',
         ];
 
+        $tab[] = [
+            'id'            => 87,
+            'table'         => $this->getTable(),
+            'field'         => 'multiline_value_replace',
+            'name'          => __('Multiline field value replace', 'datainjection'),
```
Comment (stonebuzz) [inline inc/model.class.php:534]:
```suggestion
            'name'          => __('Replacing the value of multiline text fields', 'datainjection'),
```
should be the same label as the option in plugin configuration

**Review by stonebuzz — CHANGES_REQUESTED** [review]
Can you replace  `multiline_value_replace` by `replace_multiline_value` for a better understanding ?

**Comment by JeremieMercier** [comment]
Requested changes applied

**Comment by stonebuzz** [comment]
> Can you replace  `multiline_value_replace` by `replace_multiline_value` for a better understanding ?

not that at first sight

**Comment by stonebuzz** [comment]
Hi @JeremieMercier 

can you adapt CHANGELOG ?

**Review by stonebuzz — APPROVED** [review]

**Comment by JeremieMercier** [comment]
Hi @stonebuzz,

I have update changelog, and i have remove whitespaces on files hook.php and model.class.php

File: CHANGELOG.md [hunk 3]
```diff
@@ -12,6 +12,12 @@ and this project adheres to [Semantic Versioning](http://semver.org/).
 - Use `global`  configuration for injection links
 - Escape  data when check if already exist
 
+## [2.15.0] - 2025-02-26
```
Comment (stonebuzz) [inline CHANGELOG.md:15]:
```suggestion
## [Unreleased]
```

Tag are added only when release

File: CHANGELOG.md [hunk 4]
```diff
@@ -12,6 +12,12 @@ and this project adheres to [Semantic Versioning](http://semver.org/).
...
+
+### Added
+
+- Add option to replace the value of multiline text fields
```
Comment (stonebuzz) [inline CHANGELOG.md:19]:
```suggestion
- Add option to `replace` (instead of `append`)  the value of multiline text fields (e.g. `comment`)
```

**Review by stonebuzz — CHANGES_REQUESTED** [review]

**Review by Rom1-B — APPROVED** [review]
